{% set name = "sasview" %}
{% set version = "5.0.4.post36" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/SasView/{{ name }}/archive/2596c259f132ad416b3b377aa4a78366b3d9a809.tar.gz
  sha256: 66dc5f15445eaf163c9279f7c391ae71d1c82f330b6d82d940aeb765664515b6

build:
  number: 0
  skip: true  # [win or py<36]
  entry_points:
    - sasview = sas.qtgui.MainWindow.MainWindow:run_sasview

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - numpy
    - pyqt >=5
    - setuptools
  run:
    - python
    - bumps >=0.9.0
    - dataclasses
    # See
    # https://github.com/sqlalchemy/mako/blob/86025c02f25954d7be32b368c6b015f6c9f51b71/setup.cfg#L37
    # for the importlib-metadata conditional dependency.
    - importlib-metadata  # [py<38]
    - h5py >=2.5
    - lxml
    - matplotlib-base
    - periodictable >=1.5.0
    - pillow
    - pyparsing >=2.0.0
    - pyqt >=5
    - qt5reactor
    - sasmodels >=1.0.6
    - scipy
    - twisted
    - xhtml2pdf
    - {{ pin_compatible('numpy') }}

test:
  requires:
    - pip
  imports:
    - sas.sasview
    - sas.qtgui
    - sas.qtgui.MainWindow
  commands:
    - pip check
    - which sasview

about:
  home: https://github.com/SasView/sasview
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.TXT
  summary: SasView is a Small Angle Scattering (SAS) analysis package

extra:
  recipe-maintainers:
    - mdoucet
    - mrakitin
    - rozyczko
    - stuartcampbell
