{% set name = "sasview" %}
{% set version = "6.0.0b2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/SasView/{{ name }}/archive/refs/tags/v6.0.0-beta-2.tar.gz

  sha256: a5626c90a9d417f10a302e9bec1d973aea7d4f5af94a3c3824a14487cca6ac39

build:
  number: 0
  skip: true  # [py<36]
  entry_points:
    - sasview = sas.qtgui.MainWindow.MainWindow:run_sasview

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - numpy ==1.26
    - PySide6 ==6.4
    - scipy ==1.13
    - setuptools
  run:
    - python
    - bumps
    - dataclasses
    - appdirs
    - cffi
    - docutils
    - dominate
    - h5py
    - html2text
    - html5lib
    - importlib-resources
    - ipython
    - jsonschema
    - lxml
    - mako
    - matplotlib
    - numba
    - periodictable
    - pybind11
    - pylint
    - pyopengl
    - pyparsing
    - pytest
    - pytest-mock
    - pytools
    - qtconsole
    - six
    - sphinx
    - superqt
    - twisted
    - uncertainties
    - unittest-xml-reporting
    - xhtml2pdf
    - {{ pin_compatible('numpy',max_pin='x.x') }}
    - {{ pin_compatible('scipy',max_pin='x.x') }}
    - {{ pin_compatible('PySide6',max_pin='x.x') }}
test:
  requires:
    - pip
  imports:
    - sas.sasview
    - sas.qtgui
    - sas.qtgui.MainWindow
  commands:
    - pip check
    - which sasview  # [not win]

about:
  home: https://github.com/SasView/sasview
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.TXT
  summary: SasView is a Small Angle Scattering (SAS) analysis package

extra:
  recipe-maintainers:
    - mdoucet
    - mrakitin
    - rozyczko
    - stuartcampbell
    - pbeaucage
    - wpotrzebowski
