{% set name = "sasview" %}
{% set version = "5.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/SasView/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 92752efb4593be216ccc3063e70f5868ccf779c2815547610d0bc9ba460edd36

build:
  number: 0
  skip: true  # [win or py2k]
  entry_points:
    - sasview = sas.qtgui.MainWindow.MainWindow:run_sasview

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - numpy
    - pip
    - pyqt >=5
    - python
    - setuptools
  run:
    - bumps
    - h5py >=2.5
    - lxml
    - matplotlib
    - {{ pin_compatible('numpy') }}
    - periodictable >=1.5.0
    - pillow
    - pyparsing >=2.0.0
    - pyqt >=5
    - python
    - qt5reactor
    - sasmodels
    - scipy
    - twisted <=18.4
    - xhtml2pdf

test:
  imports:
    - sas.sasview
    - sas.qtgui
    - sas.qtgui.MainWindow
  commands:
    - which sasview

about:
  home: https://github.com/SasView/sasview
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE.TXT
  summary: SasView is a Small Angle Scattering (SAS) analysis package

extra:
  recipe-maintainers:
    - mdoucet
    - mrakitin
    - rozyczko
    - stuartcampbell
