{% set name = "sasview" %}
{% set version = "5.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/SasView/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 1ea0971357effeaff1089664a2a2858a144ecbcf8538fabed8b81cbacb5d59ad

build:
  number: 0
  skip: true  # [win or py<36]
  entry_points:
    - sasview = sas.qtgui.MainWindow.MainWindow:run_sasview

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - numpy
    - pyqt >=5
    - setuptools
  run:
    - python
    - bumps
    - dataclasses
    - h5py >=2.5
    - lxml
    - matplotlib-base
    - {{ pin_compatible('numpy') }}
    - periodictable >=1.5.0
    - pillow
    - pyparsing >=2.0.0
    - pyqt >=5
    - qt5reactor
    - sasmodels
    - scipy
    - twisted
    - xhtml2pdf

test:
  requires:
    - pip
  imports:
    - sas.sasview
    - sas.qtgui
    - sas.qtgui.MainWindow
  commands:
    - pip check
    - which sasview

about:
  home: https://github.com/SasView/sasview
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.TXT
  summary: SasView is a Small Angle Scattering (SAS) analysis package

extra:
  recipe-maintainers:
    - mdoucet
    - mrakitin
    - rozyczko
    - stuartcampbell
