travis:
  secure:
    BINSTAR_TOKEN: jBglF1Pq+TeWbcj/gZirPd+che7T9KqnM4KHq5MbyDBnk/I8P8r9hvBw0SzqPzlxL5+zWtZOJ0jfv761euJUzQs0lSvIU5i3RKzwOduvK/cQvRC6iwFX6DC21WZ04NymOrgJe6Pkbe8xjbiSZwkPOs8cb8jnTNlOiYZrV/ooASnBgpXcMnWhr6MX0k8ipq3hrCoK8HmN8yHCWaEYu6jxRvCQn9Q4qbhcS4tMqtgZ//0XXEdp1E3JtrGtrZSBuLJrmXdp2KATwPpY09qmxicwdrziRZuDJvcnnkpcPRseWfj1tl6hspo284AbWMA0wN6oXJG+3G3v45bHsxD5amqPY224jTIFnaZeeM+L/LEfzR2KqJ8gdqdTEtfOxSiBr8/gF1BqUVNKMI/i3Ijnv5INF93/ZjVmzBgMXrd1SIg/5SpfzdO9oSs7sXEci7sNsxNekRnelmqxqDraj2ssS96ismujT7SIM1RRtjiiXfoQ86UHrj9aqhZRGgSvJbBFofVmDOQYrllMv8VSjTyRhhFuVI2EEJ1PQCUs5kHcoFnpa1p8d5Cxw1MzeUoMmdY1co3u67blwWHsHVZIsTSo47d+wZRqzJSgZ75EqxFf8cTCVtx4CQmH2nrEVwpGb9oOtKIRaPgFRU8C5tT2fclgBOGTF4k0H4uW4LMQPbKDtDBMIc4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
